services:
  imageproxy:
    image: imageproxy
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4593:4593"
      - "3080:80"
    volumes:
      - ./data:/var/cache/imageproxy
